/**
 * User list page tests.
 *
 * Demonstrates:
 *   - Happy-path list rendering with fixed array lengths
 *   - Nested address rendering with per-user array length control
 *   - Pagination with request-aware transform
 *
 * These tests use Playwright's `page.route()` to intercept API calls and
 * return data generated by `openapi-mocks`. This approach works in any
 * environment without requiring a service worker.
 */

import { test, expect } from "@playwright/test";
import { createMockClient } from "openapi-mocks";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const specPath = path.join(__dirname, "../specs/acme-api.yaml");

const mocks = createMockClient(specPath, {
  seed: 42,
  baseUrl: "http://localhost:4200/api/v1",
});

// ---------------------------------------------------------------------------
// 1. Happy Path – List Users with fixed array length
// ---------------------------------------------------------------------------

test.describe("User list page", () => {
  test("renders exactly 3 users returned by the API", async ({ page }) => {
    const data = await mocks.data({
      operations: {
        listUsers: {
          arrayLengths: { users: [3, 3] },
        },
      },
    });

    const listUsersData = data.get("listUsers")?.get(200) as Record<string, unknown>;
    expect(listUsersData).toBeDefined();

    // Intercept the API request and return mock data.
    await page.route("**/api/v1/users", (route) => {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          ...listUsersData,
          page: 1,
          totalPages: 1,
          nextPage: null,
        }),
      });
    });

    await page.goto("/users");

    const cards = page.locator("[data-testid='user-card']");
    await expect(cards).toHaveCount(3);
  });

  test("renders nested addresses for each user", async ({ page }) => {
    const data = await mocks.data({
      operations: {
        listUsers: {
          // 2 users, each with exactly 1 address.
          // Note: `addresses` is optional in the schema, so some users may not
          // have it generated. We use a transform to guarantee addresses are
          // present so the test can assert on the rendered output reliably.
          arrayLengths: {
            users: [2, 2],
            "users[*].addresses": [1, 1],
          },
          transform: (d) => {
            const response = d as { users?: Array<Record<string, unknown>> };
            const users = (response.users ?? []).map((user) => ({
              ...user,
              // Ensure addresses array is always present with at least 1 item.
              addresses: Array.isArray(user.addresses) && user.addresses.length > 0
                ? user.addresses
                : [{ street: "123 Main St", city: "Springfield", zip: "12345" }],
            }));
            return { ...response, users };
          },
        },
      },
    });

    const listUsersData = data.get("listUsers")?.get(200) as Record<string, unknown>;

    await page.route("**/api/v1/users", (route) => {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          ...listUsersData,
          page: 1,
          totalPages: 1,
          nextPage: null,
        }),
      });
    });

    await page.goto("/users");

    const cards = page.locator("[data-testid='user-card']");
    await expect(cards).toHaveCount(2);

    // Each user card should have exactly 1 address.
    for (const card of await cards.all()) {
      await expect(card.locator("[data-testid='address']")).toHaveCount(1);
    }
  });

  test("snapshot: seeded output is deterministic", async () => {
    // With a fixed seed, the generated data should always be the same.
    // This catches regressions in mock data generation.
    const data = await mocks.data({
      operations: {
        listUsers: {
          arrayLengths: { users: [2, 2] },
        },
      },
    });

    const listUsersData = data.get("listUsers")?.get(200) as { users: Array<{ name: string; email: string; id: string }> };
    expect(listUsersData).toBeDefined();

    // The number of users should match our pinned array length.
    expect(listUsersData.users).toHaveLength(2);

    // Each user should have the required fields.
    for (const user of listUsersData.users) {
      expect(user).toHaveProperty("id");
      expect(user).toHaveProperty("name");
      expect(user).toHaveProperty("email");
      expect(user.email).toContain("@");
    }

    // The same call with the same seed returns identical data.
    const data2 = await mocks.data({
      operations: {
        listUsers: {
          arrayLengths: { users: [2, 2] },
        },
      },
    });
    const listUsersData2 = data2.get("listUsers")?.get(200) as { users: Array<{ name: string }> };
    expect(listUsersData2.users[0]?.name).toBe(listUsersData.users[0]?.name);
  });
});

// ---------------------------------------------------------------------------
// 2. Pagination – Request-Aware Transform
// ---------------------------------------------------------------------------

test.describe("Pagination", () => {
  test("sets nextPage cursor based on query params", async ({ page }) => {
    // Generate base data once; the transform will adjust pagination fields.
    const data = await mocks.data({
      operations: {
        listUsers: {
          arrayLengths: { users: [5, 5] },
        },
      },
    });
    const baseData = data.get("listUsers")?.get(200) as Record<string, unknown>;

    // Intercept with a request-aware handler that reads the cursor param.
    await page.route("**/api/v1/users**", (route, request) => {
      const url = new URL(request.url());
      const cursor = url.searchParams.get("cursor");
      const pageNum = cursor ? parseInt(cursor, 10) : 1;

      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({
          ...baseData,
          page: pageNum,
          nextPage: pageNum < 3 ? pageNum + 1 : null,
          totalPages: 3,
        }),
      });
    });

    await page.goto("/users");

    // Page 1 is shown initially.
    await expect(page.locator("[data-testid='current-page']")).toHaveText("1");

    // Navigate to page 2.
    await page.getByRole("link", { name: "Next" }).click();
    await expect(page.locator("[data-testid='current-page']")).toHaveText("2");

    // Navigate to page 3 (last page).
    await page.getByRole("link", { name: "Next" }).click();
    await expect(page.locator("[data-testid='current-page']")).toHaveText("3");

    // No "Next" link on the last page.
    await expect(page.getByRole("link", { name: "Next" })).toBeHidden();
  });
});
