openapi: 3.1.0
info:
  title: Acme API
  version: 1.0.0
  description: A minimal API spec for the openapi-mocks Playwright example.

servers:
  - url: https://api.acme.dev/v1

paths:
  /users:
    get:
      operationId: listUsers
      summary: List all users
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A list of users with pagination info
          content:
            application/json:
              schema:
                type: object
                required:
                  - users
                  - page
                  - totalPages
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                  page:
                    type: integer
                    minimum: 1
                  nextPage:
                    type: ["integer", "null"]
                    minimum: 1
                  totalPages:
                    type: integer
                    minimum: 1
    post:
      operationId: createUser
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserInput"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

  /users/{userId}:
    get:
      operationId: getUser
      summary: Get a single user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetail"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          x-faker-method: string.uuid
        name:
          type: string
          x-faker-method: person.fullName
        email:
          type: string
          x-faker-method: internet.email
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/Address"

    UserDetail:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          x-faker-method: string.uuid
        name:
          type: string
          x-faker-method: person.fullName
        email:
          type: string
          x-faker-method: internet.email
          example: user@example.com
        settings:
          type: object
          properties:
            theme:
              type: string
              enum:
                - light
                - dark
            notifications:
              type: boolean
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/Address"

    Address:
      type: object
      required:
        - street
        - city
      properties:
        street:
          type: string
          x-faker-method: location.streetAddress
        city:
          type: string
          x-faker-method: location.city
        zip:
          type: string
          x-faker-method: location.zipCode

    CreateUserInput:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
          maxLength: 20

    ValidationError:
      type: object
      required:
        - message
        - fieldErrors
      properties:
        message:
          type: string
        fieldErrors:
          type: array
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
              message:
                type: string

    NotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
