openapi: 3.1.0
info:
  title: Products API
  version: 1.0.0
  description: A minimal API spec for the openapi-mocks mock server example.

servers:
  - url: http://localhost:3000

paths:
  /products:
    get:
      operationId: listProducts
      summary: List all products
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                required:
                  - products
                  - total
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
                    minItems: 1
                    maxItems: 10
                  total:
                    type: integer
                    minimum: 0
    post:
      operationId: createProduct
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductInput"
      responses:
        "201":
          description: Product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

  /products/{productId}:
    get:
      operationId: getProduct
      summary: Get a single product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: A product object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"

  /categories:
    get:
      operationId: listCategories
      summary: List all product categories
      responses:
        "200":
          description: A list of categories
          content:
            application/json:
              schema:
                type: object
                required:
                  - categories
                properties:
                  categories:
                    type: array
                    items:
                      $ref: "#/components/schemas/Category"

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
        - category
      properties:
        id:
          type: string
          x-faker-method: string.uuid
        name:
          type: string
          x-faker-method: commerce.productName
        description:
          type: ["string", "null"]
          x-faker-method: commerce.productDescription
        price:
          type: number
          minimum: 0.01
          x-faker-method: commerce.price
        category:
          type: string
          x-faker-method: commerce.department
        inStock:
          type: boolean
        imageUrl:
          type: ["string", "null"]
          format: uri
          x-faker-method: image.url
        createdAt:
          type: string
          format: date-time

    CreateProductInput:
      type: object
      required:
        - name
        - price
        - category
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
        price:
          type: number
          minimum: 0.01
        category:
          type: string

    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          x-faker-method: string.uuid
        name:
          type: string
          x-faker-method: commerce.department
        description:
          type: string
          x-faker-method: lorem.sentence

    ValidationError:
      type: object
      required:
        - message
        - fieldErrors
      properties:
        message:
          type: string
        fieldErrors:
          type: array
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
              message:
                type: string

    NotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Resource not found
